(table as table ) as table =>
let
    TaskFields = {"id", "accountId", "title", "status", "importance", "createdDate", "completedDate", "updatedDate", "dates", "scope", "customStatusId", "permalink", "priority","briefDescription","effortAllocation", "billingType","customItemTypeId" },
    #"Removed Columns" = if(Table.HasColumns(table,{"Column2"})) then Table.RemoveColumns(table,{"Column2"}) else table,
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Removed Columns", "Column1", TaskFields, TaskFields),
    #"Expanded dates" = Table.ExpandRecordColumn(#"Expanded Column1", "dates", {"type", "duration", "start", "due"}, {"type", "duration", "start", "due"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded dates",{{"id", type text}, {"accountId", type text}, {"title", type text}, {"importance", type text}, {"createdDate", type datetime}, {"completedDate", type datetime}, {"duration", type number}, {"start", type datetime}, {"due", type datetime}, {"updatedDate", type datetime}, {"type", type text}, {"scope", type text}, {"customStatusId", type text}, {"permalink", type text}, {"priority", type text},{"briefDescription", type text}, {"customItemTypeId", type text}})
in
    #"Changed Type"